development:
  adapter: redis
  url: <%= Rails.application.credentials[:redis][:url] %>
  channel_prefix: chatomud_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials[:redis][:url] %>
  channel_prefix: chatomud_production
